# Aplicacao
spring.application.name=secret-vault

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/playgrounddb
spring.datasource.username=playground
spring.datasource.password=playground123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Porta da aplicacao
server.port=8081

# JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Criptografia AES
encryption.key=1234567890123456
